# Enable mouse emulation.
CONFIG_ZMK_POINTING=y

# Enable pin bind
CONFIG_ZMK_BLE_PASSKEY_ENTRY=y

# Change idle settings
CONFIG_ZMK_IDLE_TIMEOUT=60000

# Deep sleep settings
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=1800000